apiVersion: apps/v1
kind: Deployment #资源类型
metadata:
  name: deployment-user-v2 # 资源名称
spec:
  selector:
    matchLabels:
      app: pod-user-v2
  replicas: 1 #声明pod的副本数量
  template:
    metadata:
      labels:
        app: pod-user-v2
    spec: #描述的是pod内的容器信息
      containers:
        - name: nginx
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret-opaque-file
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret-opaque-file
                  key: password
          image: registry.cn-beijing.aliyuncs.com/zhangrenyang/nginx:user-v2
          ports:
            - containerPort: 80 #容器内映射的端口号
