apiVersion: apps/v1
kind: Deployment #资源类型
metadata:
  name: deployment-user-v3 # 资源名称
spec:
  selector:
    matchLabels:
      app: pod-user-v3
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-user-v3
    spec:
      imagePullSecrets:
        - name: my-registry-auth
      containers:
        - name: reactproject
          image: 39.104.170.121:8082/reactproject:20210815122359
          ports:
            - containerPort: 80 #容器内映射的端口号
