apiVersion: apps/v1
kind: Deployment #资源类型
metadata:
  name: deployment-user-v3 # 资源名称
spec:
  selector:
    matchLabels:
      app: pod-user-v3
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-user-v3
    spec:
      containers:
        - name: nginx
          image: registry.cn-beijing.aliyuncs.com/zhangrenyang/nginx:user-v2
          ports:
            - containerPort: 80 #容器内映射的端口号
