apiVersion: apps/v1
kind: Deployment #资源类型
metadata:
  name: deployment-user-v5 # 资源名称
spec:
  selector:
    matchLabels:
      app: pod-user-v5
  replicas: 1 #声明pod的副本数量
  template:
    metadata:
      labels:
        app: pod-user-v5
    spec:
      volumes:
        - name: mysql-config-volume # 数据卷名称
          configMap:
            name: mysql-config # configmap 名字
      containers:
        - name: nginx
          image: registry.cn-beijing.aliyuncs.com/zhangrenyang/nginx:user-v1
          volumeMounts:
            - name: mysql-config-volume
              mountPath: /mysql-config
              readOnly: true
          ports:
            - containerPort: 80 #容器内映射的端口号
