apiVersion: apps/v1
kind: Deployment #资源类型
metadata:
  name: deployment-user-v1 # 资源名称
spec:
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pod-user-v1
  replicas: 3 #声明pod的副本数量
  template:
    metadata:
      labels:
        app: pod-user-v1
    spec: #描述的是pod内的容器信息
      containers:
        - name: nginx
          image: registry.cn-beijing.aliyuncs.com/zhangrenyang/nginx:user-v3
          ports:
            - containerPort: 80 #容器内映射的端口号
